apiVersion: v1
kind: Namespace
metadata:
  name: publisher-api-service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-api-service-pod # Base POD name
  namespace: publisher-api-service-system
spec:
  selector:
    matchLabels:
      app: api # Selector for POD name search
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: publisher-api-service
          image: publisher-api-amd64:1.0
