apiVersion: v1
kind: Namespace
metadata:
  name: jobs-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-pod # Base POD name
  namespace: jobs-system
spec:
  selector:
    matchLabels:
      app: jobs # Selector for POD name search
  template:
    metadata:
      labels:
        app: jobs
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: jobs-api
          image: jobs-api-amd64:1.0
